services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/release_notifier
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      BASE_URL: http://localhost:3000
      GITHUB_TOKEN: ""
      SCAN_CRON: "*/1 * * * *"
      REDIS_URL: redis://redis:6379
      API_KEY: ""
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: release_notifier
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
